on:
  release:
    types:
      - published
name: Build & Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@master
    - name: Get Version Number
      uses: WyriHaximus/github-action-get-previous-tag@v1
      id: lasttag
    - name: Generate wordpress.org assets
      run: /bin/bash ${PWD}/.github/bin/make-readmetxt.sh
    - name: Post to WordPress.org Plugin Directory
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    - name: Create Zip file
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: "upcoming-for-calendly-${{ steps.lasttag.outputs.tag }}.zip"
        exclusions: '*nondist *DOCKER_ENV *docker_tag *output.log *.git* *.distignore *.wordpress-org'
        directory: '..'
        path: 'upcoming-for-calendly'
    - name: Post to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        tag: ${{ steps.lasttag.outputs.tag }}
        artifacts: "../upcoming-for-calendly-${{ steps.lasttag.outputs.tag }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
